### ISSUE TITLE
LateInitializationError: Field 'dynamicLibrary' has not been initialized

### ISSUE THREAD

**Issue by mbfakourii** [physia/kflutter#5]
```
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: LateInitializationError: Field 'dynamicLibrary' has not been initialized.
#0      dynamicLibrary (package:dart_vlc_ffi/src/internal/dynamiclibrary.dart)
#1      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart:20:42)
#2      PlayerFFI.create (package:dart_vlc_ffi/src/internal/ffi.dart)
#3      new Player (package:dart_vlc_ffi/src/player.dart:108:15)
#4      new Player (package:dart_vlc/dart_vlc.dart:56:9)
#5      new Player (package:kplayer_with_dart_vlc/kplayer_with_dart_vlc.dart:18:27)
#6      Player.create (package:kplayer/kplayer.dart:50:23)
#7      Player.asset (package:kplayer/kplayer.dart:73:19)
```

**Comment by mbfakourii** [comment]
```
import 'package:kplayer_with_dart_vlc/fake_dart_vlc.dart'
    if (dart.library.ffi) 'package:dart_vlc/dart_vlc.dart' hide Player;

DartVLC.initialize();

var player = Player.asset("assets/sound_alarm.mp3", autoPlay: false);
player.play();
```
